Improve arch and system autodetection #52
marwanhawari/stew pull request #57
Opened 2024-10-17 10:56 UTC by slavaGanzin

Before:
```bash
stew i rancher-sandbox/rancher-desktop
rancher-sandbox/rancher-desktop
! Could not automatically detect the release asset matching your OS/Arch. Please select it manually:  [Use arrows to move, type to filter]
> rancher-desktop-linux-v1.16.0.zip
  rancher-desktop-linux-v1.16.0.zip.sha512sum
  Rancher.Desktop-1.16.0-mac.aarch64.zip
  Rancher.Desktop-1.16.0-mac.aarch64.zip.sha512sum
  Rancher.Desktop-1.16.0-mac.x86_64.zip
  Rancher.Desktop-1.16.0-mac.x86_64.zip.sha512sum
  Rancher.Desktop-1.16.0.aarch64.dmg
```

After:
```bash
stew i rancher-sandbox/rancher-desktop
rancher-sandbox/rancher-desktop
! Could not automatically detect the release asset matching your OS/Arch. Please select it manually:  [Use arrows to move, type to filter]
> Rancher.Desktop-1.16.0-mac.x86_64.zip
  Rancher.Desktop-1.16.0.x86_64.dmg
```

```bash
uname -a
Darwin m 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112 x86_64
```

2024-12-27 15:20 UTC, slavaGanzin commented
@marwanhawari ?

2025-01-19 19:15 UTC, marwanhawari requested changes

2025-01-19 19:15 UTC, marwanhawari commented on constants/constants.go
Could you remove `.dmg` and `.appx`? Don't think these help because even if you can download them you want be able to properly install these formats through stew.

2025-01-19 19:15 UTC, marwanhawari commented on lib/github.go
> +			finalAsset, err = WarningPromptSelect("Could not automatically detect the release asset matching your OS/Arch. Please select it manually:", detectedFinalAssets)
I think if filtering fails, I'd rather be conservative and show the user everything, so could you please revert this?

2025-01-19 19:15 UTC, marwanhawari commented on lib/github.go
> +		if re.MatchString(asset) {
Can you move this to the `constants.go` file? Include a comment like:

```go
// RegexChecksum is a regular expression for matching checksum files
var RegexChecksum = `\.(sha(256|512)(sum)?)$`
```

2025-01-19 23:24 UTC, slavaGanzin commented on lib/github.go
> +			finalAsset, err = WarningPromptSelect("Could not automatically detect the release asset matching your OS/Arch. Please select it manually:", detectedFinalAssets)
Ok

But can we add some logic around interactive and non-I reactive terminals? I use stew in docker installations and “I will show you everything” is not working well in this scenario

2025-01-19 23:26 UTC, slavaGanzin commented on lib/github.go
> +			finalAsset, err = WarningPromptSelect("Could not automatically detect the release asset matching your OS/Arch. Please select it manually:", detectedFinalAssets)
Yes it can be an option, but everybody will forget it on a first run. Just like -y is always forgotten in “apt install package“ in scripts

2025-01-20 04:55 UTC, marwanhawari commented on lib/github.go
> +			finalAsset, err = WarningPromptSelect("Could not automatically detect the release asset matching your OS/Arch. Please select it manually:", detectedFinalAssets)
For non-interactive installs, you should be installing from a `Stewfile.lock.json`.

```sh
stew install Stewfile.lock.json
```

2025-01-20 10:29 UTC, slavaGanzin commented on lib/github.go
> +			finalAsset, err = WarningPromptSelect("Could not automatically detect the release asset matching your OS/Arch. Please select it manually:", detectedFinalAssets)
Eh. It will not work this way. I'm on Mac, my container is linux and maybe on different architecture

2025-01-21 01:31 UTC, marwanhawari commented
Merged in your commit + small changes in https://github.com/marwanhawari/stew/pull/65

Thank you for your contribution!!

2025-01-21 01:31 UTC, closed without merging